use std::ops::{Deref, DerefMut};

use mraphics_core::{InstanceUpdater, MeshLike, Representable, Transformable};

use crate::Mobject2D;

pub struct Segment {
    inner: Mobject2D,
}

impl Default for Segment {
    fn default() -> Self {
        Self::new([-1.0, 0.0, 0.0], [1.0, 0.0, 0.0])
    }
}

impl Segment {
    pub fn new(start: [f32; 3], end: [f32; 3]) -> Self {
        let mut inner = Mobject2D::new();
        inner.move_to(start);
        inner.line_to(end);
        inner.stroke();

        Self { inner }
    }
}

// TODO: Manually written for now, will be generated by a macro later.
impl Deref for Segment {
    type Target = Mobject2D;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl DerefMut for Segment {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}

impl InstanceUpdater for Segment {
    fn update_instance(&self, instance: &mut mraphics_core::RenderInstance) {
        self.inner.update_instance(instance);
    }
}

impl MeshLike for Segment {
    fn identifier(&self) -> mraphics_core::MraphicsID {
        self.inner.identifier()
    }

    fn build_instance(&self) -> mraphics_core::RenderInstance {
        self.inner.build_instance()
    }

    fn update(&mut self) {
        self.inner.update();
    }
}

impl Representable for Segment {
    type Intermediate = <Mobject2D as Representable>::Intermediate;

    fn as_intermediate(&self) -> Self::Intermediate {
        self.inner.as_intermediate()
    }

    fn update_from_intermediate(&mut self, repr: &Self::Intermediate) {
        self.inner.update_from_intermediate(repr);
    }
}

impl Transformable for Segment {
    fn apply_transform<Trans: Fn(&[f32; 3]) -> [f32; 3]>(
        &self,
        transform: Trans,
    ) -> Self::Intermediate {
        self.inner.apply_transform(transform)
    }
}
